dukaan_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('seller/', include('sellerSide.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellerSide/urls.py
from sellerSide import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'sellerSide'

urlpatterns = [

    path('', views.sellerHome, name="sellerHome"),
    path('register/', views.register , name="sellerRegister"),
    path('login/', views.login_attempt, name="sellerLogin"),
    path('verify_otp/', views.verify_otp, name="verify_otp"),
    path('login_verify_otp/', views.login_otp, name="login_otp"),
    path('inventory/', views.SellerInventoryView.as_view(), name="sellerInventory"),
    path('opened-stores/', views.SellerStoresView.as_view(), name="sellerStores"),
    path('new/store/', views.SellerNewStoreView.as_view(), name="sellerNewStore"),
    path('new/product/', views.SellerNewProductView.as_view(), name="sellerNewProduct"),
    path('profile/', views.SellerProfileView.as_view(), name="sellerProfile"),
    path('logout/', auth_views.LogoutView.as_view(next_page='sellerSide:sellerHome'), name='sellerLogout'),
]

sellerSide/models.py
from django.db import models
from django.contrib.auth.models import User
import random



# Create your models here.

random_string = "!@#$%^&(){}<>?'+_"

class Account(models.Model):
    userid = models.AutoField(primary_key=True, default=1)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=30)
    otp = models.CharField(max_length=6)

    @property
    def issued_token_to_user(self):
        return f"USR_token_{random.shuffle(random_string)}&&{self.mobile[:3]}"

    def __str__(self):
        return f" {self.user}, user is created"


class Store(models.Model):
    storeid = models.AutoField(primary_key=True)
    userid = models.ForeignKey(Account, on_delete=models.CASCADE)
    store_name = models.CharField(max_length=20)
    store_city = models.CharField(max_length=30)
    store_state = models.CharField(max_length=30)
    store_pincode = models.CharField(max_length=30)
    
    @property
    def store_link(self):
        return f"{self.store_name}_&_{random.shuffle(random_string)}"
    
    def __str__(self):
        return f"Store created with name {self.store_name}"



class Product(models.Model):
    productid = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=30)
    product_desc = models.TextField()
    product_mrp = models.FloatField()
    product_salePrice = models.FloatField()
    product_image = models.ImageField(upload_to="product_images")
    product_cat = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"product {self.product_name}"


# class Categories(models.Model):
#     id = models.AutoField(primary_key=True)
#     product_name = models.ForeignKey(Product, on_delete=models.CASCADE)


class Customer(models.Model):
    customerid = models.AutoField(primary_key=True)
    customer_mobile = models.CharField(max_length=13, unique=True)
    customer_name = models.CharField(max_length=50)
    customer_city = models.CharField(max_length=30)
    customer_state = models.CharField(max_length=30)
    customer_pincode = models.CharField(max_length=30)

    def __str__(self):
        return f"customer with name {self.customer_name}"


class Order(models.Model):
    orderid = models.AutoField(primary_key=True)
    productid = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer_mobile = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return f"order details for customer mobile {self.customer_mobile} with {self.product_name}"

sellerSide/views.py
from django.shortcuts import redirect, render
from django.views import View
from .models import Account
from django.contrib.auth.models import User
import random
from .send_otp_Django import sendOTP
from django.contrib.auth import authenticate, login



# Create your views here.

def sellerHome(request):
    return render(request, "seller_home.html")

def login_attempt(request):
    if request.method == 'POST':
        mobile = request.POST.get('mobile')
        
        user = Account.objects.filter(mobile = mobile).first()
        print("mobile-------------------->")
        if user is None:
            context = {'message' : 'User not found' , 'class' : 'danger' }
            return render(request,'seller_login.html' , context)
        
        otp = str(random.randint(1000 , 9999))
        user.otp = otp
        user.save()
        sendOTP(mobile , otp)
        request.session['mobile'] = mobile
        return redirect('sellerSide:login_otp')        
    return render(request,'seller_login.html')


def login_otp(request):
    mobile = request.session['mobile']
    context = {'mobile':mobile}
    print("login_otp is called")
    if request.method == 'POST':
        otp = request.POST.get('otp')
        profile = Account.objects.filter(mobile=mobile).first()
        
        if otp == profile.otp:
            user = User.objects.get(id = profile.user.id)
            login(request , user)
            return redirect('sellerSide:sellerHome')
        else:
            context = {'message' : 'Wrong OTP' , 'class' : 'danger','mobile':mobile }
            return render(request,'seller_login_otp.html' , context)
    
    return render(request,'seller_login_otp.html' , context)

def register(request):
    if request.method == "POST":
        email = request.POST.get("email")
        name = request.POST.get("name")
        mobile = request.POST.get("mobile")

        check_accounts = Account.objects.filter(mobile=mobile).first()
        check_users = Account.objects.filter(mobile=mobile).first()

        if check_accounts or check_users:
            context = {"message":"User already exist with this email or mobile number", "class":"danger"}
            return render(request, 'seller_registration.html', context)

        user = User(email=email, first_name=name)
        user.save()

        # generating OTP
        otp = str(random.randint(100000, 999999))

        profile = Account(user=user, mobile=mobile, otp=otp)
        profile.save()
        sendOTP(mobile, otp)

        # creating session for user mobile number for OTP verification
        request.session["mobile"] = mobile
        return redirect('sellerSide:verify_otp') # calling below otp function

    return render(request, 'seller_registration.html')


def verify_otp(request):
    # getting data from session
    mobile = request.session["mobile"]
    context = {'mobile':mobile}
    if request.method == "POST":
        otp = request.POST.get("otp")
        profile = Account.objects.filter(mobile=mobile).first()
        if otp == profile.otp:
            return redirect('sellerSide:sellerHome')
        else:
            context = {"message":"send OTP again", "class":"danger", 'mobile':mobile}
            return render(request, 'otp.html', context)
    return render(request, 'otp.html')

class SellerInventoryView(View):
    def get(self, request):
        return render(request, "seller_inventory.html")

class SellerStoresView(View):
    def get(self, request):
        return render(request, "seller_stores.html")

class SellerNewStoreView(View):
    def get(self, request):
        return render(request, "seller_new_store.html")

class SellerNewProductView(View):
    def get(self, request):
        return render(request, "seller_new_product.html")

class SellerProfileView(View):
    def get(self, request):
        return render(request, "seller_profile.html")

sellerSide/templates/otp.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}OTP{% endblock title %}

{% block body_content %}


<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your number {{mobile}}</h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row my-4">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'sellerSide:sellerRegister' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>

{% endblock body_content %}

sellerSide/templates/seller_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}">

    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">


    <title>Seller | {% block title %} {% endblock title %} </title>
  </head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'sellerSide:sellerHome'%}">MyDukaan</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sellerSide:sellerStores' %}">Opened Stores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sellerSide:sellerInventory' %}">Inventory</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sellerSide:sellerNewStore' %}">Add new Store</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sellerSide:sellerNewProduct' %}">Add new Product</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  My Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'sellerSide:sellerProfile' %}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'sellerSide:sellerLogout'%}">Logout</a></li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sellerSide:sellerNewProduct' %}">About Us</a>
              </li>
              {% endif %}
            </ul>
            {% if not request.user.is_authenticated %}
            <a href="{% url 'sellerSide:sellerLogin'%}"><button class="btn btn-outline-success me-4" type="submit">Sign In</button></a>
            <a href="{% url 'sellerSide:sellerRegister'%}"><button class="btn btn-outline-primary me-4" type="submit">Register</button></a>
            {% endif %}
          </div>
        </div>
    </nav>
    {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
      {% endif %}

    {% block body_content %}{% endblock body_content %}


    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

sellerSide/templates/seller_home.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block body_content %}

<h1>Welcome user at home page</h1>

{% endblock body_content %}

sellerSide/templates/seller_inventory.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Inventory{% endblock title %}

{% block body_content %}

<h1>Your Inventory coming soon</h1>

{% endblock body_content %}

sellerSide/templates/seller_login.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block body_content %}

<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Login</h3>
        <form method="POST">
            {% csrf_token %}
            <div class="row my-4">
                <div class="form-group col-12">
                    <input type="text" placeholder="Mobile" class="form-control" name="mobile" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'sellerSide:sellerRegister' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>

{% endblock body_content %}

sellerSide/templates/seller_login_otp.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Registration{% endblock title %}

{% block body_content %}

<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your number {{mobile}}</h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'sellerSide:sellerLogin' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>

{% endblock body_content %}

sellerSide/templates/seller_new_product.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}New Product{% endblock title %}

{% block body_content %}

<h1>Now you can add new product also to your store</h1>

{% endblock body_content %}

sellerSide/templates/seller_new_store.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}New Store{% endblock title %}

{% block body_content %}

<h1>You can create a new store on this page</h1>

{% endblock body_content %}

sellerSide/templates/seller_profile.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block body_content %}

<h1>Profile coming soon</h1>

{% endblock body_content %}

sellerSide/templates/seller_registration.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Registration{% endblock title %}

{% block body_content %}

<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Register</h3>
        <form method="post">
            {% csrf_token %}

            {% if message %}
            <div class="alert alert-{{class}}">
                {{message}}
            </div>
            {% endif %}

            <div class="row my-4">
                <div class="form-group col-12">
                    <input type="text" placeholder="Email" class="form-control" name="email" id="">
                </div>
            </div>
            <div class="row my-4">
                <div class="form-group col-12">
                    <input type="text" placeholder="Name" class="form-control" name="name" id="">
                </div>
            </div>
            <div class="row my-4">
                <div class="form-group col-12">
                    <input type="text" placeholder="Mobile" class="form-control" name="mobile" id="">
                </div>
            </div>

            <p>Already have account <a href="{% url 'sellerSide:sellerLogin' %}">Login</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>

{% endblock body_content %}

sellerSide/templates/seller_stores.html
{% extends 'seller_base.html' %}
{% load static %}

{% block title %}Stores{% endblock title %}

{% block body_content %}

<h1>You can see your stores here soon</h1>

{% endblock body_content %}